HDFS-15611. Add list Snapshot command in WebHDFS.
apache/hadoop pull request #2355
Opened 2020-10-01 13:12 UTC by bshashikant

please check https://issues.apache.org/jira/browse/HDFS-15611

2020-10-02 03:43 UTC, szetszwo requested changes
Thanks @bshashikant .  Should we add `SnapshotStatus[] getSnapshotListing(Path snapshotRoot)`
to FileSystem?  If yes, we should move SnapshotStatus to org.apache.hadoop.fs and declare dirStatus using FileStatus.

2020-10-02 03:43 UTC, szetszwo commented on hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/web/JsonUtilClient.java
> +        contentEquals("DELETED");
Use "DELETED".equal(..) in order to avoid NPE?
` final boolean isDeleted = "DELETED".equals(json.get("deletionStatus"));`

2020-10-02 03:43 UTC, szetszwo commented on hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/web/WebHdfsFileSystem.java
> +  public SnapshotStatus[] getSnapshotList(final Path snapshotDir)
In DistributedFileSystem, it is called
`  public SnapshotStatus[] getSnapshotListing(Path snapshotRoot)`
Let's use the same name?

2020-10-02 03:43 UTC, szetszwo commented on hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/protocol/SnapshotStatus.java
> +import org.apache.hadoop.util.StringUtils;
Unused import.

2020-10-02 03:43 UTC, szetszwo commented on hadoop-hdfs-project/hadoop-hdfs-httpfs/src/main/java/org/apache/hadoop/fs/http/client/HttpFSFileSystem.java
> +  public SnapshotStatus[] getSnapshotList(Path snapshotRoot)
It should call getSnapshotListing.

2020-10-02 05:43 UTC, bshashikant commented
> Thanks @bshashikant . Should we add `SnapshotStatus[] getSnapshotListing(Path snapshotRoot)`
> to FileSystem? If yes, we should move SnapshotStatus to org.apache.hadoop.fs and declare dirStatus using FileStatus.

Thanks @szetszwo . I checked the code and saw that "getSnapshottableDirectoryList()" is also not moved to Filesystem class yet. I would prefer no to move any of these to Filesystem class here.

2020-10-02 07:02 UTC, szetszwo approved these changes
+1 the change looks good.

2020-10-06 16:43 UTC, smengcl approved these changes
+1

I compiled, ran the NN manually and tested the new API on a non-snapshottable directory, 0-3 snapshots, then removed snapshots one by one and rechecked the listing. Works fine.

Thanks @bshashikant for the patch!

2020-10-07 05:04 UTC, merged

2020-10-07 05:06 UTC, bshashikant commented
Thanks @szetszwo and @smengcl for the review. The 2 checkstyle issues reported are not addressed for better readability of the code. The unit test failures are not related.