HDFS-15834. Remove the usage of org.apache.log4j.Level
apache/hadoop pull request #2696
Opened 2021-02-12 07:35 UTC by aajisaka

JIRA: https://issues.apache.org/jira/browse/HDFS-15834

There are still some usages of org.apache.log4j.Level. They cannot simply be removed because they are used with Log4J1 Appender API and so on. I think they can be removed when upgraded to Log4j2.

2021-02-12 13:38 UTC, hadoop-yetus commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  18m 13s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  2s |  |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |   |   0m  0s | [test4tests](test4tests) |  The patch appears to include 76 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  14m 22s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  22m 45s |  |  trunk passed  |
| +1 :green_heart: |  compile  |   5m  4s |  |  trunk passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  compile  |   4m 23s |  |  trunk passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| +1 :green_heart: |  checkstyle  |   1m 58s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   3m 22s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  18m 40s |  |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 36s |  |  trunk passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  javadoc  |   3m 25s |  |  trunk passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| +0 :ok: |  spotbugs  |   1m 11s |  |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +0 :ok: |  findbugs  |   0m 24s |  |  branch/hadoop-hdfs-project/hadoop-hdfs-native-client no findbugs output file (findbugsXml.xml)  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 26s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 46s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   4m 38s |  |  the patch passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| -1 :x: |  javac  |   4m 38s | [/diff-compile-javac-hadoop-hdfs-project-jdkUbuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2696/1/artifact/out/diff-compile-javac-hadoop-hdfs-project-jdkUbuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04.txt) |  hadoop-hdfs-project-jdkUbuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04 with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04 generated 4 new + 692 unchanged - 79 fixed = 696 total (was 771)  |
| +1 :green_heart: |  compile  |   4m 21s |  |  the patch passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| -1 :x: |  javac  |   4m 21s | [/diff-compile-javac-hadoop-hdfs-project-jdkPrivateBuild-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2696/1/artifact/out/diff-compile-javac-hadoop-hdfs-project-jdkPrivateBuild-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08.txt) |  hadoop-hdfs-project-jdkPrivateBuild-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08 with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08 generated 4 new + 669 unchanged - 79 fixed = 673 total (was 748)  |
| -0 :warning: |  checkstyle  |   1m 46s | [/diff-checkstyle-hadoop-hdfs-project.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2696/1/artifact/out/diff-checkstyle-hadoop-hdfs-project.txt) |  hadoop-hdfs-project: The patch generated 1 new + 1630 unchanged - 4 fixed = 1631 total (was 1634)  |
| +1 :green_heart: |  mvnsite  |   2m 52s |  |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  12m 45s |  |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 19s |  |  the patch passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  javadoc  |   3m  0s |  |  the patch passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| +0 :ok: |  findbugs  |   0m 20s |  |  hadoop-hdfs-project/hadoop-hdfs-native-client has no data from findbugs  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 21s |  |  hadoop-hdfs-client in the patch passed.  |
| +1 :green_heart: |  unit  | 190m 35s |  |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  unit  |   8m 15s |  |  hadoop-hdfs-native-client in the patch passed.  |
| -1 :x: |  unit  |  17m  4s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs-rbf.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2696/1/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs-rbf.txt) |  hadoop-hdfs-rbf in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 48s |  |  The patch does not generate ASF License warnings.  |
|  |   | 362m 16s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.fs.contract.router.TestRouterHDFSContractCreate |
|   | hadoop.fs.contract.router.TestRouterHDFSContractCreateSecure |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2696/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2696 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux 6fc46ea67fc6 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / f9a073c6c18 |
| Default Java | Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2696/1/testReport/ |
| Max. process+thread count | 3348 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs-client hadoop-hdfs-project/hadoop-hdfs hadoop-hdfs-project/hadoop-hdfs-native-client hadoop-hdfs-project/hadoop-hdfs-rbf U: hadoop-hdfs-project |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2696/1/console |
| versions | git=2.25.1 maven=3.6.3 findbugs=4.0.6 |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

2021-02-14 05:31 UTC, dineshchitlangia requested changes
@aajisaka Thank you for the contribution.
Overall the changes are fine, I would be happy to merge this once the issues flagged by CI are addressed.
The test failure in unrelated to your patch though.

2021-02-15 08:10 UTC, hadoop-yetus commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 31s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  2s |  |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |   |   0m  0s | [test4tests](test4tests) |  The patch appears to include 76 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  14m 34s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  20m  6s |  |  trunk passed  |
| +1 :green_heart: |  compile  |   4m 49s |  |  trunk passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  compile  |   4m 27s |  |  trunk passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| +1 :green_heart: |  checkstyle  |   1m 55s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   3m 22s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  18m 39s |  |  branch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 33s |  |  trunk passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  javadoc  |   3m 21s |  |  trunk passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| +0 :ok: |  spotbugs  |   1m 14s |  |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +0 :ok: |  findbugs  |   0m 22s |  |  branch/hadoop-hdfs-project/hadoop-hdfs-native-client no findbugs output file (findbugsXml.xml)  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 27s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 50s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   4m 41s |  |  the patch passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  javac  |   4m 41s |  |  hadoop-hdfs-project-jdkUbuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04 with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04 generated 0 new + 692 unchanged - 79 fixed = 692 total (was 771)  |
| +1 :green_heart: |  compile  |   4m 21s |  |  the patch passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| +1 :green_heart: |  javac  |   4m 21s |  |  hadoop-hdfs-project-jdkPrivateBuild-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08 with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08 generated 0 new + 669 unchanged - 79 fixed = 669 total (was 748)  |
| +1 :green_heart: |  checkstyle  |   1m 49s |  |  hadoop-hdfs-project: The patch generated 0 new + 1630 unchanged - 4 fixed = 1630 total (was 1634)  |
| +1 :green_heart: |  mvnsite  |   2m 48s |  |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  1s |  |  The patch has no whitespace issues.  |
| +1 :green_heart: |  shadedclient  |  12m 44s |  |  patch has no errors when building and testing our client artifacts.  |
| +1 :green_heart: |  javadoc  |   2m 17s |  |  the patch passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  javadoc  |   3m  7s |  |  the patch passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| +0 :ok: |  findbugs  |   0m 19s |  |  hadoop-hdfs-project/hadoop-hdfs-native-client has no data from findbugs  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 20s |  |  hadoop-hdfs-client in the patch passed.  |
| +1 :green_heart: |  unit  | 193m 15s |  |  hadoop-hdfs in the patch passed.  |
| +1 :green_heart: |  unit  |   8m 15s |  |  hadoop-hdfs-native-client in the patch passed.  |
| -1 :x: |  unit  |  16m 50s | [/patch-unit-hadoop-hdfs-project_hadoop-hdfs-rbf.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2696/2/artifact/out/patch-unit-hadoop-hdfs-project_hadoop-hdfs-rbf.txt) |  hadoop-hdfs-rbf in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 44s |  |  The patch does not generate ASF License warnings.  |
|  |   | 344m 19s |  |  |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hadoop.fs.contract.router.web.TestRouterWebHDFSContractCreate |
|   | hadoop.fs.contract.router.TestRouterHDFSContractCreate |
|   | hadoop.fs.contract.router.TestRouterHDFSContractCreateSecure |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2696/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/2696 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient findbugs checkstyle |
| uname | Linux a0c35157c9b1 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / c3134ab3a99 |
| Default Java | Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2696/2/testReport/ |
| Max. process+thread count | 3548 (vs. ulimit of 5500) |
| modules | C: hadoop-hdfs-project/hadoop-hdfs-client hadoop-hdfs-project/hadoop-hdfs hadoop-hdfs-project/hadoop-hdfs-native-client hadoop-hdfs-project/hadoop-hdfs-rbf U: hadoop-hdfs-project |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-2696/2/console |
| versions | git=2.25.1 maven=3.6.3 findbugs=4.0.6 |
| Powered by | Apache Yetus 0.13.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

2021-02-15 09:44 UTC, aajisaka commented
Filed https://issues.apache.org/jira/browse/HDFS-15836 to fix the test failures.

2021-02-17 06:59 UTC, dineshchitlangia approved these changes
+1 LGTM @aajisaka  thank you for the improvement.

2021-02-17 06:59 UTC, merged