HADOOP-18037 : Backport HADOOP-17796 for branch-3.2
apache/hadoop pull request #3757
Opened 2021-12-07 10:10 UTC by AnanyaSingh2121

Update Jetty to 9.4.41 or above in branch-3.2

2021-12-07 11:18 UTC, hadoop-yetus commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   8m 16s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
|||| _ branch-3.2 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  26m  6s |  |  branch-3.2 passed  |
| +1 :green_heart: |  compile  |   0m 18s |  |  branch-3.2 passed  |
| +1 :green_heart: |  mvnsite  |   0m 23s |  |  branch-3.2 passed  |
| +1 :green_heart: |  javadoc  |   0m 22s |  |  branch-3.2 passed  |
| +1 :green_heart: |  shadedclient  |  40m  1s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 15s |  |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 12s |  |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 12s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  mvnsite  |   0m 14s |  |  the patch passed  |
| +1 :green_heart: |  xml  |   0m  1s |  |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 13s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  14m 59s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 16s |  |  hadoop-project in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 31s |  |  The patch does not generate ASF License warnings.  |
|  |   |  66m 39s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3757/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/3757 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient codespell xml |
| uname | Linux 44ff1e902142 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | branch-3.2 / b951eb6ec84ed30fd8d422d2512b571afe0d40ee |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~18.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3757/1/testReport/ |
| Max. process+thread count | 450 (vs. ulimit of 5500) |
| modules | C: hadoop-project U: hadoop-project |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-3757/1/console |
| versions | git=2.17.1 maven=3.6.0 |
| Powered by | Apache Yetus 0.14.0-SNAPSHOT https://yetus.apache.org |


This message was automatically generated.

2021-12-22 05:38 UTC, jojochuang requested changes
Please update LICENSE-binary file. This way, it also triggers all tests.

2021-12-22 05:39 UTC, jojochuang commented
The latest Jetty CVE affects up to 9.4.42. https://www.cvedetails.com/cve/CVE-2021-34429/ So bumping the version to 9.4.43 is a good idea.

I would suggest to revise the subject to "Update Jetty to 9.4.43" to make it clear.

2022-02-02 11:38 UTC, aajisaka commented
The LICENSE-binary file is added since 3.3.0 and this PR for branch-3.2. That's why you don't need to update the LICENSE-binary file.

2022-02-02 11:39 UTC, aajisaka approved these changes

2022-02-02 11:41 UTC, merged

2022-02-02 11:43 UTC, aajisaka commented
Thank you @AnanyaSingh2121 for your contribution.