HADOOP-18981. moved oncrpc/portmap from hadoop-common-project/hadoop-nfs to hadoop-common-project/hadoop-common
apache/hadoop pull request #6280
Opened 2023-11-19 06:49 UTC by xinglin

### Description of PR

We want to use udpserver/client for other use cases, rather than only for NFS. One such use case is to export NameNodeHAState for NameNodes via a UDP server. 

### How was this patch tested?

No change to file content. Just a bunch of renames. will wait for jenkins build results.

### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'HADOOP-17799. Your PR title ...')?
- [ ] Object storage: have the integration tests been executed and the endpoint declared according to the connector-specific documentation?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE`, `LICENSE-binary`, `NOTICE-binary` files?

2023-11-19 11:13 UTC, hadoop-yetus commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |  17m 34s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  2s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 22 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  13m 50s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  35m 36s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  18m 53s |  |  trunk passed with JDK Ubuntu-11.0.20.1+1-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  compile  |  17m 13s |  |  trunk passed with JDK Private Build-1.8.0_382-8u382-ga-1~20.04.1-b05  |
| +1 :green_heart: |  checkstyle  |   1m 26s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   2m 16s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   1m 49s |  |  trunk passed with JDK Ubuntu-11.0.20.1+1-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javadoc  |   1m 25s |  |  trunk passed with JDK Private Build-1.8.0_382-8u382-ga-1~20.04.1-b05  |
| +1 :green_heart: |  spotbugs  |   3m 25s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  37m 47s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 30s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 15s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 28s |  |  the patch passed with JDK Ubuntu-11.0.20.1+1-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javac  |  17m 28s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  16m 27s |  |  the patch passed with JDK Private Build-1.8.0_382-8u382-ga-1~20.04.1-b05  |
| +1 :green_heart: |  javac  |  16m 27s |  |  the patch passed  |
| -1 :x: |  blanks  |   0m  0s | [/blanks-eol.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6280/1/artifact/out/blanks-eol.txt) |  The patch has 145 line(s) that end in blanks. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| -1 :x: |  blanks  |   0m  0s | [/blanks-tabs.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6280/1/artifact/out/blanks-tabs.txt) |  The patch 1 line(s) with tabs.  |
| +1 :green_heart: |  checkstyle  |   1m 21s |  |  the patch passed  |
| +1 :green_heart: |  mvnsite  |   2m 13s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   1m 45s |  |  the patch passed with JDK Ubuntu-11.0.20.1+1-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javadoc  |   1m 25s |  |  the patch passed with JDK Private Build-1.8.0_382-8u382-ga-1~20.04.1-b05  |
| +1 :green_heart: |  spotbugs  |   3m 42s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  38m  5s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  19m 13s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 42s |  |  hadoop-nfs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 58s |  |  The patch does not generate ASF License warnings.  |
|  |   | 262m 32s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6280/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/6280 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell detsecrets |
| uname | Linux 1cfb4a839586 5.15.0-88-generic #98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 4c07298ee5789ef6c975c16725f01b461d113ec6 |
| Default Java | Private Build-1.8.0_382-8u382-ga-1~20.04.1-b05 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.20.1+1-post-Ubuntu-0ubuntu120.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_382-8u382-ga-1~20.04.1-b05 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6280/1/testReport/ |
| Max. process+thread count | 3069 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-common-project/hadoop-nfs U: hadoop-common-project |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6280/1/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

2023-11-20 04:39 UTC, hadoop-yetus commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 50s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  2s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 22 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  15m 11s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  35m 42s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  18m  4s |  |  trunk passed with JDK Ubuntu-11.0.20.1+1-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  compile  |  16m 33s |  |  trunk passed with JDK Private Build-1.8.0_382-8u382-ga-1~20.04.1-b05  |
| +1 :green_heart: |  checkstyle  |   1m 25s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   2m 17s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   1m 53s |  |  trunk passed with JDK Ubuntu-11.0.20.1+1-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javadoc  |   1m 27s |  |  trunk passed with JDK Private Build-1.8.0_382-8u382-ga-1~20.04.1-b05  |
| +1 :green_heart: |  spotbugs  |   3m 23s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  39m  0s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 30s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 13s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 16s |  |  the patch passed with JDK Ubuntu-11.0.20.1+1-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javac  |  17m 16s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  16m 39s |  |  the patch passed with JDK Private Build-1.8.0_382-8u382-ga-1~20.04.1-b05  |
| +1 :green_heart: |  javac  |  16m 39s |  |  the patch passed  |
| -1 :x: |  blanks  |   0m  0s | [/blanks-eol.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6280/2/artifact/out/blanks-eol.txt) |  The patch has 6 line(s) that end in blanks. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| +1 :green_heart: |  checkstyle  |   1m 21s |  |  hadoop-common-project: The patch generated 0 new + 100 unchanged - 2 fixed = 100 total (was 102)  |
| +1 :green_heart: |  mvnsite  |   2m 14s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   1m 44s |  |  the patch passed with JDK Ubuntu-11.0.20.1+1-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javadoc  |   1m 26s |  |  the patch passed with JDK Private Build-1.8.0_382-8u382-ga-1~20.04.1-b05  |
| +1 :green_heart: |  spotbugs  |   3m 40s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  37m 46s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  19m 11s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 41s |  |  hadoop-nfs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 57s |  |  The patch does not generate ASF License warnings.  |
|  |   | 246m 32s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6280/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/6280 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell detsecrets |
| uname | Linux 9d8630f26a19 5.15.0-88-generic #98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / cb36abf3837fc3840c3cc01fba723583b056da6c |
| Default Java | Private Build-1.8.0_382-8u382-ga-1~20.04.1-b05 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.20.1+1-post-Ubuntu-0ubuntu120.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_382-8u382-ga-1~20.04.1-b05 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6280/2/testReport/ |
| Max. process+thread count | 1261 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-common-project/hadoop-nfs U: hadoop-common-project |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6280/2/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

2023-11-20 09:26 UTC, hadoop-yetus commented
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 49s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  2s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 22 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  14m  4s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  35m 13s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  18m  3s |  |  trunk passed with JDK Ubuntu-11.0.20.1+1-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  compile  |  16m 31s |  |  trunk passed with JDK Private Build-1.8.0_382-8u382-ga-1~20.04.1-b05  |
| +1 :green_heart: |  checkstyle  |   1m 24s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   2m 15s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   1m 51s |  |  trunk passed with JDK Ubuntu-11.0.20.1+1-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javadoc  |   1m 26s |  |  trunk passed with JDK Private Build-1.8.0_382-8u382-ga-1~20.04.1-b05  |
| +1 :green_heart: |  spotbugs  |   3m 25s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  37m 50s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 30s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 12s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 10s |  |  the patch passed with JDK Ubuntu-11.0.20.1+1-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javac  |  17m 10s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  16m 16s |  |  the patch passed with JDK Private Build-1.8.0_382-8u382-ga-1~20.04.1-b05  |
| +1 :green_heart: |  javac  |  16m 16s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   1m 19s |  |  hadoop-common-project: The patch generated 0 new + 100 unchanged - 2 fixed = 100 total (was 102)  |
| +1 :green_heart: |  mvnsite  |   2m 13s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   1m 45s |  |  the patch passed with JDK Ubuntu-11.0.20.1+1-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javadoc  |   1m 26s |  |  the patch passed with JDK Private Build-1.8.0_382-8u382-ga-1~20.04.1-b05  |
| +1 :green_heart: |  spotbugs  |   3m 40s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  37m 57s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  19m 11s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 40s |  |  hadoop-nfs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 57s |  |  The patch does not generate ASF License warnings.  |
|  |   | 243m 24s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6280/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/6280 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell detsecrets |
| uname | Linux d3695b4c0f33 5.15.0-88-generic #98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 8b2bb0a199f0d28b8a887a40030ff2d1290c7ff8 |
| Default Java | Private Build-1.8.0_382-8u382-ga-1~20.04.1-b05 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.20.1+1-post-Ubuntu-0ubuntu120.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_382-8u382-ga-1~20.04.1-b05 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6280/3/testReport/ |
| Max. process+thread count | 1261 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-common-project/hadoop-nfs U: hadoop-common-project |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6280/3/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

2023-11-20 21:45 UTC, xinglin commented
@goiri / @ZanderXu, can I get a review? thanks,

2023-12-04 20:10 UTC, simbadzina commented
If I understand correctly you just need `SimpleUdpClient` and `SimpleUdpServer`. Can you not use them while there are still in this location?

Moving files and the widespread whitespace changes will make future small backports difficult, unless this commit is also backported.

2023-12-04 21:36 UTC, xinglin commented
The key point is if we use UDPClient/server from other module, then it becomes inappropriate to put this under hadoop-common-project/hadoop-nfs module. And if we don't fix it now but build upon this, it would make code harder to maintain and would take more work if we want to fix it in the future. 

Another example is the key-value Interface/implementation. Right now, YARN uses a key-value store to store some persistent data and they put key-value interface/implementation in YARN module. However, we may look into store persistent k/v pairs too for HDFS. We should move key-value interface/implemention into hadoop-common, rather than adding a dependency on YARN from HDFS.

I still remember a lesson I learned from reading John Ousterhout's "a philosophy of software engineering" book: when we make a change to an existing system, we should make the new change such that the new change seems to be designed from the beginning. On the other hand, most of us tend to try minimizing line of changes, which ideally shouldn't not be a concern.

2023-12-07 02:39 UTC, xinglin commented
@simbadzina / @goiri / @ZanderXu / @Hexiaoqiao Can i get a review? What do you guys think of this PR? Thanks,

2023-12-11 20:08 UTC, simbadzina commented
The PR looks ok to me. My only concern is the number of files that are moved and changed. I'll wait for the other to chime in.
@xinglin do you plan on working on the following
```
export NameNodeHAState for NameNodes via a UDP server.
```
Make this jira as a subtask of that one may provide better context.

2023-12-12 17:53 UTC, xinglin commented
thanks @simbadzina for providing your comments. I created HADOOP-18981 and linked it to this jira.

2023-12-20 06:16 UTC, xinglin commented
@Hexiaoqiao, @goiri, @ZanderXu, thoughts? Could we move forward?

2023-12-24 09:30 UTC, Hexiaoqiao commented
@xinglin @simbadzina Thanks for your works. +1 from my side. The only concern is that is it compatible changes to end user if dependency with oncrpc/portmap? Thanks.

2023-12-24 23:46 UTC, xinglin commented
> @xinglin @simbadzina Thanks for your works. +1 from my side. The only concern is that is it compatible changes to end user if dependency with oncrpc/portmap? Thanks.

That is a good point: previously, whoever depends on oncrpc/portmap would have a dependency on hadoop-nfs module. With this relocation, they need to change dependency to be hadoop-common module.

2023-12-25 04:56 UTC, Hexiaoqiao commented
> This should be the only change, as we did not rename package names/paths.

It's OK for me if only check in branch-3.4, and we should mark 'Incompatible changes' flag when check in. Thanks.

2023-12-25 05:25 UTC, xinglin commented
That makes sense. Thanks for reviewing and offering advice!

2024-01-01 20:14 UTC, steveloughran requested changes
LGTM

I wouldn't even consider it as incompatible...it's just moving classes around.

one thing I would propose is for the new packages to have package-info.java files describing the modules as @Private .

2024-01-01 20:18 UTC, steveloughran commented
Note that as hadoop-common is a provided dependency of hadoop-nfs, with explicit use of `org.apache.hadoop.util` classes in `MountdBase`, is there any deployment/use of the hadoop-nfs module without hadoop-common in the cp?

2024-01-04 06:41 UTC, xinglin commented
@steveloughran, Thanks for taking a look at this change. I added a couple of package-info.java files. First time doing this and not sure whether I am adding these files correctly. Could you take a look?

2024-01-04 07:02 UTC, xinglin commented
> Note that as hadoop-common is a provided dependency of hadoop-nfs, with explicit use of org.apache.hadoop.util classes in MountdBase, is there any deployment/use of the hadoop-nfs module without hadoop-common in the cp?

If this is the case, I guess we can be assured that hadoop-common is always available whenever hadoop-nfs is needed/depended. And moving classes around as done by this PR won't break these other modules which used to be depended on hadoop-nfs module. Am i understanding it correctly?

2024-01-04 10:50 UTC, hadoop-yetus commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 51s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  2s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  0s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  0s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 22 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  14m  6s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  37m 47s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  18m 55s |  |  trunk passed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  compile  |  18m 19s |  |  trunk passed with JDK Private Build-1.8.0_392-8u392-ga-1~20.04-b08  |
| +1 :green_heart: |  checkstyle  |   2m  8s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   2m 14s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   1m 46s |  |  trunk passed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javadoc  |   1m 22s |  |  trunk passed with JDK Private Build-1.8.0_392-8u392-ga-1~20.04-b08  |
| +1 :green_heart: |  spotbugs  |   3m 28s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  40m 20s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 30s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 14s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  18m 17s |  |  the patch passed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javac  |  18m 17s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 41s |  |  the patch passed with JDK Private Build-1.8.0_392-8u392-ga-1~20.04-b08  |
| +1 :green_heart: |  javac  |  17m 41s |  |  the patch passed  |
| -1 :x: |  blanks  |   0m  0s | [/blanks-eol.txt](https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6280/4/artifact/out/blanks-eol.txt) |  The patch has 3 line(s) that end in blanks. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| +1 :green_heart: |  checkstyle  |   1m 25s |  |  hadoop-common-project: The patch generated 0 new + 97 unchanged - 5 fixed = 97 total (was 102)  |
| +1 :green_heart: |  mvnsite  |   2m 16s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   1m 44s |  |  the patch passed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javadoc  |   1m 24s |  |  the patch passed with JDK Private Build-1.8.0_392-8u392-ga-1~20.04-b08  |
| +1 :green_heart: |  spotbugs  |   3m 57s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  38m 12s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  19m 10s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 41s |  |  hadoop-nfs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 59s |  |  The patch does not generate ASF License warnings.  |
|  |   | 256m 19s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6280/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/6280 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell detsecrets |
| uname | Linux 42bcb0fdcb39 5.15.0-88-generic #98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / 8869a890c335c882802276b087503a08e5e3f5d1 |
| Default Java | Private Build-1.8.0_392-8u392-ga-1~20.04-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu120.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_392-8u392-ga-1~20.04-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6280/4/testReport/ |
| Max. process+thread count | 3137 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-common-project/hadoop-nfs U: hadoop-common-project |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6280/4/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

2024-01-04 22:36 UTC, hadoop-yetus commented
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime |  Logfile | Comment |
|:----:|----------:|--------:|:--------:|:-------:|
| +0 :ok: |  reexec  |   0m 50s |  |  Docker mode activated.  |
|||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  |  No case conflicting files found.  |
| +0 :ok: |  codespell  |   0m  1s |  |  codespell was not available.  |
| +0 :ok: |  detsecrets  |   0m  1s |  |  detect-secrets was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  |  The patch appears to include 22 new or modified test files.  |
|||| _ trunk Compile Tests _ |
| +0 :ok: |  mvndep  |  21m 14s |  |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  35m 39s |  |  trunk passed  |
| +1 :green_heart: |  compile  |  20m 25s |  |  trunk passed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  compile  |  18m 27s |  |  trunk passed with JDK Private Build-1.8.0_392-8u392-ga-1~20.04-b08  |
| +1 :green_heart: |  checkstyle  |   1m 24s |  |  trunk passed  |
| +1 :green_heart: |  mvnsite  |   2m 16s |  |  trunk passed  |
| +1 :green_heart: |  javadoc  |   1m 50s |  |  trunk passed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javadoc  |   1m 25s |  |  trunk passed with JDK Private Build-1.8.0_392-8u392-ga-1~20.04-b08  |
| +1 :green_heart: |  spotbugs  |   3m 22s |  |  trunk passed  |
| +1 :green_heart: |  shadedclient  |  38m 23s |  |  branch has no errors when building and testing our client artifacts.  |
|||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 31s |  |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 13s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  17m 19s |  |  the patch passed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javac  |  17m 19s |  |  the patch passed  |
| +1 :green_heart: |  compile  |  16m 26s |  |  the patch passed with JDK Private Build-1.8.0_392-8u392-ga-1~20.04-b08  |
| +1 :green_heart: |  javac  |  16m 26s |  |  the patch passed  |
| +1 :green_heart: |  blanks  |   0m  0s |  |  The patch has no blanks issues.  |
| +1 :green_heart: |  checkstyle  |   1m 20s |  |  hadoop-common-project: The patch generated 0 new + 97 unchanged - 5 fixed = 97 total (was 102)  |
| +1 :green_heart: |  mvnsite  |   2m 13s |  |  the patch passed  |
| +1 :green_heart: |  javadoc  |   1m 45s |  |  the patch passed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javadoc  |   1m 27s |  |  the patch passed with JDK Private Build-1.8.0_392-8u392-ga-1~20.04-b08  |
| +1 :green_heart: |  spotbugs  |   3m 41s |  |  the patch passed  |
| +1 :green_heart: |  shadedclient  |  38m  3s |  |  patch has no errors when building and testing our client artifacts.  |
|||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  19m  9s |  |  hadoop-common in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 39s |  |  hadoop-nfs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 58s |  |  The patch does not generate ASF License warnings.  |
|  |   | 256m 57s |  |  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6280/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/hadoop/pull/6280 |
| Optional Tests | dupname asflicense compile javac javadoc mvninstall mvnsite unit shadedclient spotbugs checkstyle codespell detsecrets |
| uname | Linux e1025f51ef65 5.15.0-88-generic #98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev-support/bin/hadoop.sh |
| git revision | trunk / e41b03e94606a508644011f4d61bcdb1f8516a92 |
| Default Java | Private Build-1.8.0_392-8u392-ga-1~20.04-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu120.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_392-8u392-ga-1~20.04-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6280/5/testReport/ |
| Max. process+thread count | 3137 (vs. ulimit of 5500) |
| modules | C: hadoop-common-project/hadoop-common hadoop-common-project/hadoop-nfs U: hadoop-common-project |
| Console output | https://ci-hadoop.apache.org/job/hadoop-multibranch/job/PR-6280/5/console |
| versions | git=2.25.1 maven=3.6.3 spotbugs=4.2.2 |
| Powered by | Apache Yetus 0.14.0 https://yetus.apache.org |


This message was automatically generated.

2024-01-09 22:39 UTC, xinglin commented
@steveloughran / @Hexiaoqiao please help move this PR forward. thanks,

2024-01-09 23:27 UTC, jojochuang commented
I am +1, having been probably the last person maintaining the NFS code myself. Had a quick pass of the PR. Seems fine.

On a side note, hadoop-common is used by many many applications, even indirectly. It's likely anything you add to hadoop-common implicitly makes countless applications bloated unfortunately. I don't really care now given how powerful bare metal machines are, but someone in the kubernetes or docker world might complain. I see that the PR doesn't introduce additional dependencies in pom.xml so it's good.

2024-01-11 14:01 UTC, steveloughran approved these changes
LGTM
+1

2024-01-11 14:06 UTC, merged

2024-01-14 05:36 UTC, xinglin commented
Glad to see it got merged! Thanks for everyone for your reviews!